FROM node:20 AS build
WORKDIR /app

COPY FrontEnd/package*.json ./
RUN npm install

COPY FrontEnd/ ./
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist/front-app/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
